# To use the config file, use the -c/--config option pointing to the path of a config file

# Config for blutgang goes here
[blutgang]
# Clear the cache DB on startup
clear_cache = false
# Address to bind blutgang to
address = "127.0.0.1"
# Port to bind blutgang to
port = 3000
# Moving average length for the latency
ma_length = 100
# Sort RPCs by latency on startup. Recommended to leave on.
sort_on_startup = true
# Enable health checking
health_check = true
# Enable content type header checking. Set this to `true` if you want
# Blutgang to be JSON-RPC compliant.
header_check = true
# Acceptable time to wait for a response in ms
ttl = 30
# How many times to retry a request before giving up
max_retries = 32
# Block time in ms, used as a sanity check when not receiving subscriptions
expected_block_time = 13000
# Time between health checks in ms
health_check_ttl = 400
# Supress the health check running info messages
supress_rpc_check = false

# Note: the admin namespace contains volatile functions and
# should not be exposed publicly. Values can be provided directly
# for testing, but it's recommended to configure an admin file
# and provide the path.
[blutgang.admin]
# Path to a privileged admin config
path = "./blutgang-admin.toml"
# Enable the admin namespace
enable = false
# Address for the admin RPC
address = "127.0.0.1"
# Port for the admin RPC
port = 5715
# Only allow read-only methods
# Recommended `true` unless you 100% need write methods
readonly = true
# Enable the use of JWT for auth
# Should be on if exposing to the internet
jwt = false
# jwt token
key = ""

# Sled config
# Sled is one of the databases we use for our cache, for more info check their docs
# https://docs.rs/sled/1.0.0-alpha.124/sled/struct.Config.html
[blutgang.db.sled]
# Enable sled as the database used for caching
enable = true
# Path to db
path = "./blutgang-cache-sled"
# Cache size in bytes.
cache_capacity = 1000000000
# Select zstd compression level. Reduces size 60-70%,
# and increases CPU and latency by around 10% for db writes and 2% for reads
compression = 1
# Frequency of flushes in ms
flush_every_ms = 12000

# TODO: @eureka-cpu -- add rocksdb options here
# 
# RocksDB config
# RocksDB is one of the databases we use for our cache, for more info check their docs
# https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide
[blutgang.db.rocksdb]
# Enable rocksdb as the database used for caching
enable = false
# Path to db
path = "./blutgang-cache-rocksdb"

# TODO: @eureka-cpu -- probably a good idea to make sure we need an id, other than the url
# id is optional, if left empty the id is derived from the url field
# but this does not guarantee unique ids
#
# Add separate RPCs as an array of TOML tables
[[rpc]]
id = "merkle"
url = "https://eth.merkle.io"
ws_url = "wss://eth.merkle.io"
# The maximum amount of time we can use this rpc in a row.
max_consecutive = 150
# Max amount of queries per second.
max_per_second = 200
